version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - web_data:/usr/share/nginx/html
    ports:
      - "1984:80"

  modifier:
    build:
      context: .
      dockerfile: Dockerfile.modif
    volumes:
      - web_data:/data

volumes:
  web_data:
